### ISSUE TITLE
Memory usage of data-api grows over time then drops and repeats

### ISSUE THREAD

**Issue by phutchins** [Storj/data-api#6]
Version: 0.0.1

<img width="954" alt="screen_shot_2016-06-13_at_9 34 11_am" src="https://cloud.githubusercontent.com/assets/1074345/16521861/c8562df2-3f67-11e6-911a-a3090e33e3b0.png">

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
